[[repeller]]
name = "Левый отпугиватель test1"
type = "test"
camera = "cam1"

[[repeller]]
name = "Правый отпугиватель test1"
type = "test"
camera = "cam1"

[[repeller]]
name = "Левый отпугиватель test2"
type = "test"
camera = "cam2"

[[repeller]]
name = "Правый отпугиватель test2"
type = "test"
camera = "cam2"

[[camera]]
name = "Тестовая камера"
url = "rtmp://localhost/live/test"
enable = true
track = true
test = true

[[camera]]
name = "Реальная камера"
url = "rtmp://localhost/live/test2"
enable = true
track = true

[model]
name = "yolo26s"
fuse = true
test = false
test_delay = 1
verbose = false

[application]
enable_web_ui = true
enable_config_api = false
logging_level = "info"
name = "Cow Reppelent System"
